### ISSUE TITLE
Crash when using OptaScheduler

### ISSUE THREAD

**Issue by tiquionophist** [tiquionophist/hhs-scheduler#11]
Some users have reported a crash, which may be related to their runtime. In a brief test I wasn't able to reproduce.

```
java.lang.RuntimeException: Instance of NATIVE compiler cannot be created!
   at org.kie.memorycompiler.JavaCompilerFactory.lambda$loadCompiler$0(JavaCompilerFactory.java:33)
   at java.base/java.util.Optional.orElseThrow(Unknown Source)
   at org.kie.memorycompiler.JavaCompilerFactory.loadCompiler(JavaCompilerFactory.java:33)
   at org.kie.memorycompiler.JavaCompilerFactory.loadCompiler(JavaCompilerFactory.java:29)
   at org.kie.memorycompiler.JavaCompilerFactory.loadCompiler(JavaCompilerFactory.java:25)
   at org.kie.memorycompiler.KieMemoryCompiler.compileNoLoad(KieMemoryCompiler.java:127)
   at org.kie.memorycompiler.KieMemoryCompiler.compileNoLoad(KieMemoryCompiler.java:101)
   at org.kie.memorycompiler.KieMemoryCompiler.compile(KieMemoryCompiler.java:53)
   at org.kie.memorycompiler.KieMemoryCompiler.compile(KieMemoryCompiler.java:39)
   at org.drools.ancompiler.KieBaseUpdaterANC.inMemoryUpdate(KieBaseUpdaterANC.java:66)
   at org.drools.ancompiler.KieBaseUpdaterANC.run(KieBaseUpdaterANC.java:52)
   at org.drools.ancompiler.KieBaseUpdaterANC.generateAndSetInMemoryANC(KieBaseUpdaterANC.java:99)
   at org.optaplanner.core.impl.score.director.stream.DroolsConstraintStreamScoreDirectorFactory.buildKieBaseFromModel(DroolsConstraintStreamScoreDirectorFactory.java:115)
   at org.optaplanner.core.impl.score.director.stream.DroolsConstraintStreamScoreDirectorFactory.buildKieBase(DroolsConstraintStreamScoreDirectorFactory.java:104)
   at org.optaplanner.core.impl.score.director.stream.DroolsConstraintStreamScoreDirectorFactory.<init>(DroolsConstraintStreamScoreDirectorFactory.java:71)
   at org.optaplanner.core.impl.score.director.ScoreDirectorFactoryFactory.buildConstraintStreamScoreDirectorFactory(ScoreDirectorFactoryFactory.java:223)
   at org.optaplanner.core.impl.score.director.ScoreDirectorFactoryFactory.decideMultipleScoreDirectorFactories(ScoreDirectorFactoryFactory.java:103)
   at org.optaplanner.core.impl.score.director.ScoreDirectorFactoryFactory.buildScoreDirectorFactory(ScoreDirectorFactoryFactory.java:71)
   at org.optaplanner.core.impl.solver.DefaultSolverFactory.buildScoreDirectorFactory(DefaultSolverFactory.java:116)
   at org.optaplanner.core.impl.solver.DefaultSolverFactory.buildSolver(DefaultSolverFactory.java:83)
   at com.tiquionophist.scheduler.OptaScheduler.schedule(OptaScheduler.kt:77)
   at com.tiquionophist.ui.RunScheduleButtonKt$RunScheduleButton$2$5$1.invokeSuspend(RunScheduleButton.kt:153)
   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by tiquionophist** [comment]
Fixed by https://github.com/tiquionophist/hhs-scheduler/commit/83e84bd5a01d0685e9543f4867899a2b0e7bd4d3 since Opta scheduler has been removed (due to this and other issues)
